### ISSUE TITLE
Documentation for log levels

### ISSUE THREAD

**Issue by xuhcc** [ipfs/kubo#7808]
#### Location

https://github.com/ipfs/go-ipfs/blob/master/docs/environment-variables.md#ipfs_logging

#### Description

The document says that logging level for `IPFS_LOGGING` variable should be one of `CRITICAL ERROR WARNING NOTICE INFO DEBUG`.
`ipfs log --help` says that supported levels are `debug, info, warn, error, dpanic, panic, fatal`.

But it seems that none of these is working with `IPFS_LOGGING` (the output is not affected).

Also, the GitHub issue template and readme point to https://github.com/ipfs/docs which is archived:

```
Problems with documentation on https://docs.ipfs.io should be reported to https://github.com/ipfs/docs
```

**Comment by aschmahmann** [comment]
@xuhcc thanks for the heads up on the Github template, btw the repo is now ipfs/ipfs-docs as noted in the archived ipfs/docs repo.

> But it seems that none of these is working with IPFS_LOGGING (the output is not affected).

Can you give more information, i.e. the recommendation in the bug report template of `ipfs version --all`?

Running the below commands gives me tons of log output in the terminal the daemon is running in.
```
export IPFS_LOGGING=DEBUG
ipfs daemon
```

**Comment by xuhcc** [comment]
go-ipfs version:

```
$ ipfs version --all
go-ipfs version: 0.7.0-ea77213e3
Repo version: 10
System version: amd64/linux
Golang version: go1.15.2
```

Logger output:

```
$ IPFS_LOGGING=CRITICAL ipfs log tail
error setting log levels: unrecognized level: "CRITICAL"
...(lots of seemingly low-level log records)...

$ IPFS_LOGGING=fatal ipfs log tail
...(also lots of low-level log records but no unrecognized level error)...
```

**Comment by xuhcc** [comment]
I see, `IPFS_LOGGING=fatal` works with `ipfs daemon`. So `ipfs log tail` is some other kind of log.

**Comment by aschmahmann** [comment]
Yes `ipfs log tail` is a different kind of log then the one emitted by `ipfs daemon`. From the docs:

```
> ipfs log tail --help
USAGE
  ipfs log tail - Read the event log.

SYNOPSIS
  ipfs log tail

DESCRIPTION

  Outputs event log messages (not other log messages) as they are generated.

```

btw issue template bug fixed by #7809

**Comment by xuhcc** [comment]
This issue is about documentation which is still not updated.

**Comment by aschmahmann** [comment]
Ah, I see the issue is that the mismatch between the doc and help function with one having `CRITICAL WARNING NOTICE` and the other `warn, dpanic, panic, fatal`.

**Comment by gammazero** [comment]
The documentation has been updated to reflect the same log levels as the log command.
